version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_admin
      MYSQL_USER: aas
      MYSQL_PASSWORD: andon
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    env_file:
      - ./client/.env

volumes:
  mysql_data:
