GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWI4ZTU2NGVhNWNlMTE0MTg0Y2NiOTYiLCJlbWFpbCI6ImRlbW9AZ21haWwuY29tIiwiaXNWZXJpZmllZCI6dHJ1ZSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTcyODU3NDI5OCwiZXhwIjoxNzMxMTY2Mjk4fQ.nHPldURmzSV0XIS9vjGEURzWZ8Ibh2-Jv45uLjra5p4
###
// Register
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "abla4",
    "email": "abla4@gmail.com",
    "username": "abla4",
    "password": "44444",
    "confPassword": "44444"
}
###
// Login 
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "abla3@gmail.com",
    "password": "33333"
} 
###
// after login, refresh token when expired
GET http://localhost:5000/token
###
// delete token
DELETE http://localhost:5000/logout


###
// tb_product
GET http://localhost:5000/products

